skip-check: &skip-check
  name: Check for [ci skip]
  command: bash .circleci/early_exit.sh

merge-check: &merge-check
  name: Check if we need to merge upstream master
  command: |
    if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
      git fetch origin --tags
      git fetch origin +refs/pull/$CIRCLE_PR_NUMBER/merge:pr/$CIRCLE_PR_NUMBER/merge
      git checkout -qf pr/$CIRCLE_PR_NUMBER/merge
    fi
apt-run: &apt-install
  name: Install apt packages
  command: |
    sudo apt update
    sudo apt install -y gfortran swig libfftw3-dev
tox-install: &tox-install
  name: Install Tox
  command: |
    pip install tox
image-run: &image-tests
  name: Run image tests
  environment:
    MPLBACKEND: Agg
  command: |
    python setup.py test
version: 2
jobs:
  egg-info-36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: *skip-check
      - run: *merge-check
      - run: python setup.py egg_info

  egg-info-37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: *skip-check
      - run: *merge-check
      - run: python setup.py egg_info

  pip-install:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: *skip-check
      - run: *merge-check
      - run: *apt-install
      - run:
          name: Update pip
          command: sudo pip install -U pip
      - run:
          name: install numpy
          command: pip install --user numpy wheel | cat
      - run:
          name: install dependencies
          command: pip install --user toml obspy | cat
      - run:
          name: Build hashwrap
          command: python setup.py bdist_wheel | cat

  32bit:
    docker:
      - image: i386/ubuntu:latest
    steps:
      - checkout
      - run: *skip-check
      - run:
          name: apt dependencies
          command: |
            export DEBIAN_FRONTEND="noninteractive"
            apt-get update
            apt install -y gfortran swig libfftw3-dev
      - run:
          name: Install dependencies one
          # Cat here to suppress the progress bar
          command: pip3 install cython obspy toml | cat
      - run:
          name: Run tests
          command: PYTHONHASHSEED=42 python3 setup.py test --parallel=4
    environment:
      MPLBACKEND: agg
      COLUMNS: 180

workflows:
  version: 2

  pip-install:
    jobs:
      - pip-install

  # build-32:
  #   jobs:
  #     - 32bit
